### ISSUE TITLE
Not as fast as expected

### ISSUE THREAD

**Issue by komorogrov** [veltavid/HNPFuzzer#2]
It's a very excellent job. Thanks for authors to release `HNPFuzzer`.

But, I found that `HNPFuzzer` only runs at `30~50msg/s`, which is even slower than the `AFLNet`.  According to the data in your paper, the speed reaches `2129.93 msg/s` in the same experimental environment (Ubuntu 20.04 16GB RAM).

This low speed should not happen. Is there any parameter I forgot to set when  running `HNPFuzzer`?

Running Command line:
`~/HNPFuzzer/afl-fuzz -m none  -d -i ~/HNPFuzzer/tutorials/lightftp/in-ftp -o ./out-lightftp-hnp-0123 -N tcp://127.0.0.1/2200 -x ~/HNPFuzzer/tutorials/lightftp/ftp.dict -P FTP -D 10000 -q 3 -s 3 -E -R -c ./ftpclean.sh ./fftp fftp.conf 2200
`

HNPFuzzer
![HNPFuzzer-question-1](https://github.com/veltavid/HNPFuzzer/assets/30967717/6b4f6f81-ae9d-4f60-ab7d-fcc05fd596a1)

AFLNet
![aflnet-1](https://github.com/veltavid/HNPFuzzer/assets/30967717/df33b5ba-7d28-4cf8-a471-ef6419ef6634)

**Comment by veltavid** [comment]
The reason might be the same as #1 , please try the scripts provided in [HNPFuzzer-ProFuzzBench](https://github.com/veltavid/HNPFuzzer-ProFuzzBench).

**Comment by komorogrov** [comment]
Thanks for your patient.
I set the environment variable `export AFL_PRELOAD=${HNPFUZZER}/sock2shm.so` when running the above experiments.
I also tried the scripts provided by HNPFuzzer-ProFuzzBench after your response, but got similar experimental results.

`HNPFuzzer` running 1 hours
![屏幕截图 2024-02-06 223937](https://github.com/veltavid/HNPFuzzer/assets/30967717/7a4fd542-617d-4895-b3be-7f06ffc0054e)

Experiment results
![屏幕截图 2024-02-06 223428](https://github.com/veltavid/HNPFuzzer/assets/30967717/95924dfa-ce0f-4d12-997e-6f4e81a23388)

`AFLNet` running1 hours

![exec_speed](https://github.com/veltavid/HNPFuzzer/assets/30967717/6502a93a-4972-4e17-8d94-9600c9f4da56)

I am still very confused by the experimental results, because in theory the method proposed in the paper should work. Therefore, your further help is greatly appreciated.

**Comment by veltavid** [comment]
> Thanks for your patient. I set the environment variable `export AFL_PRELOAD=${HNPFUZZER}/sock2shm.so` when running the above experiments. I also tried the scripts provided by HNPFuzzer-ProFuzzBench after your response, but got similar experimental results.
> 
> `HNPFuzzer` running 1 hours ![屏幕截图 2024-02-06 223937](https://private-user-images.githubusercontent.com/30967717/302667107-7a4fd542-617d-4895-b3be-7f06ffc0054e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQzNDQsIm5iZiI6MTcwODE0NDA0NCwicGF0aCI6Ii8zMDk2NzcxNy8zMDI2NjcxMDctN2E0ZmQ1NDItNjE3ZC00ODk1LWIzYmUtN2YwNmZmYzAwNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ODVhNTM2ODI2NjMxYzIzYmZlNGU0MDA0ZDVkOWJhZTMyZjExYjhlNzZmMjA0MjZjNTFhOWE0NDMwM2QwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hh4qCSALWHFubbUlD7mig_Zsbqk0ZeJViao0NI5bSwc)
> 
> Experiment results ![屏幕截图 2024-02-06 223428](https://private-user-images.githubusercontent.com/30967717/302666099-95924dfa-ce0f-4d12-997e-6f4e81a23388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQzNDQsIm5iZiI6MTcwODE0NDA0NCwicGF0aCI6Ii8zMDk2NzcxNy8zMDI2NjYwOTktOTU5MjRkZmEtY2UwZi00ZDEyLTk5N2UtNmY0ZTgxYTIzMzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYWE0OGVjZWM4NzdjZmE0OWIyYzg1NzMzMDJmZTQ0MjgwZmU5NTJjYzMwNDA3MWNiYjViYjEyOWFmNThjYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ew1MDDHblWPQ4jQKveTLlf5g55GLESwu3jcdNPBHflU)
> 
> `AFLNet` running1 hours
> 
> ![exec_speed](https://private-user-images.githubusercontent.com/30967717/302669011-6502a93a-4972-4e17-8d94-9600c9f4da56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQzNDQsIm5iZiI6MTcwODE0NDA0NCwicGF0aCI6Ii8zMDk2NzcxNy8zMDI2NjkwMTEtNjUwMmE5M2EtNDk3Mi00ZTE3LThkOTQtOTYwMGM5ZjRkYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTNlMGZiZjlkNjAzNWUyZGIzNDg4ZGYxNjI4NDFhZDdlOGVkNjZjMTYzY2NmZTg1MzlkOGQ1M2QxMjg5NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bl6Vso_2AvkeoL5I5mLwloaY-DPc6Ehdv8u7g5kBKV8)
> 
> I am still very confused by the experimental results, because in theory the method proposed in the paper should work. Therefore, your further help is greatly appreciated.

Hello @komorogrov. Have you built docker images according to [profuzzbench_build_HNPFuzzer.sh](https://github.com/veltavid/HNPFuzzer-ProFuzzBench/blob/master/scripts/execution/profuzzbench_build_HNPFuzzer.sh)? It may also be related to hardware? I don't know.

I just ran the experiments using the scripts provided in HNPFuzzer-ProFuzzBench on my machine and all went smoothly. So it is not likely that I have uploaded the wrong resources.

![lightftp-aflnet](https://github.com/veltavid/HNPFuzzer/assets/58317658/9ca398a7-6ce4-483d-a2eb-bb92390b5919)

![lightftp-HNPFuzzer](https://github.com/veltavid/HNPFuzzer/assets/58317658/be3f6449-51d5-438c-a545-e647ccf1f862)

**Comment by komorogrov** [comment]
Hello [veltavid](https://github.com/veltavid)
Thank you very much for your effort and patience. I have reproduced the experiment after set number of runs to 1.
`./run_target.sh -t lightftp -r 1 -f HNPFuzzer -m all -o ./tmp_results`
